### ISSUE TITLE
Keine individuelle Einstellung 

### ISSUE THREAD

**Issue by SirNio** [BugPlayZ/CustomHitboxes#1]
Sofern ich nur die Hitboxes für die Player aktivieren möchte, geht dies nicht. 
Es gibt nur die Möglichkeit sich von allen Objekten im Spiel die Hitbox anzeigen zu lassen oder von gar keinen.

**Comment by BugPlayZ** [comment]
Hey, ich bin mir diesem bewusst, hab allerdings derzeit nicht die Zeit, mich mit dem Addon auseinanderzusetzen. Wenn du nun Hitboxen nur für Spieler aktivieren möchtest, musst du einfach bei den anderen Typen "Custom" aktivieren und bei der Farbe den Alpha-Wert auf 0 setzen

LG
